import {
  Pencil, Trash2, Eye, EyeOff, X, Check, CheckCircle, Plus, Minus,
  DollarSign, Wallet, Banknote, BarChart3, TrendingUp, TrendingDown,
  User, Users, AlertTriangle, Bell, Phone, ChevronDown, ChevronLeft,
  ArrowRight, Menu, LogOut, Calendar, Clock, MapPin, Star, Zap,
  Ban, Archive, Loader2, MessageCircle, Search, Package, Home,
  ClipboardCheck, Trophy, ClipboardList, Shield, Wallet as WalletIcon,
  FileText, Settings,
} from 'lucide-react';

const map: Record<string, React.ComponentType<{ className?: string }>> = {
  editar: Pencil,
  eliminar: Trash2,
  ver: Eye,
  ocultar: EyeOff,
  cerrar: X,
  confirmar: Check,
  verificar: CheckCircle,
  agregar: Plus,
  quitar: Minus,
  dinero: DollarSign,
  billetera: Wallet,
  efectivo: Banknote,
  grafica: BarChart3,
  subida: TrendingUp,
  bajada: TrendingDown,
  usuario: User,
  usuarios: Users,
  alerta: AlertTriangle,
  campana: Bell,
  telefono: Phone,
  abajo: ChevronDown,
  izquierda: ChevronLeft,
  derecha: ArrowRight,
  menu: Menu,
  salir: LogOut,
  calendario: Calendar,
  reloj: Clock,
  ubicacion: MapPin,
  estrella: Star,
  rayo: Zap,
  bloqueo: Ban,
  archivar: Archive,
  cargando: Loader2,
  whatsapp: MessageCircle,
  buscar: Search,
  paquete: Package,
  inicio: Home,
  asistencias: ClipboardCheck,
  torneos: Trophy,
  convocatorias: ClipboardList,
  entrenamientos: Zap,
  partidos: Shield,
  caja: WalletIcon,
  inventario: Package,
  notas: FileText,
  cobranzas: Bell,
  bitacora: ClipboardList,
  configuracion: Settings,
};

export function Icon({ name, className = 'w-5 h-5' }: { name: string; className?: string }) {
  const Cmp = map[name];
  if (!Cmp) return null;
  const extra = name === 'cargando' ? ' animate-spin' : '';
  return <Cmp className={className + extra} />;
}
